config/routes.rb
Rails.application.routes.draw do

  resources :convos
  root 'convos#index'
  post 'callback' => 'convos#callback'

end

app/models/convo.rb
class Convo < ActiveRecord::Base
end

app/controllers/application_controller.rb
# require 'sinatra'
require 'line/bot'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/convos_controller.rb
class ConvosController < ApplicationController
  before_action :client

  def index
    @convos = Convo.all
  end

  def new
    @convo = Convo.new
  end

  def create
    convo = Convo.new(convo_params)
    if convo.save!
      redirect_to convos_path
    else
      render :new
    end
  end

# Line bot
  def callback 
    signature = request.env['HTTP_X_LINE_CHANNELSIGNATURE']
    unless client.validate_signature(request.body.read, signature)
      error 400 do 'Bad Request' end
    end

    receive_request = Line::Bot::Receive::Request.new(request.env)

    receive_request.data.each { |message|
      case message.content
      when Line::Bot::Message::Text
        client.send_text(
          to_mid: message.from_mid,
          text: message.content[:text] + " --- by Pu <3 @ 531",
        )
      end
    }
    head :ok    
  end


  private

  def convo_params
    params.require(:convo).permit(:text)
  end

# Line bot
  def client
    @client ||= Line::Bot::Client.new { |config|
      # binding.pry
      config.channel_id = ENV["LINEPUBOT_ID"]
      config.channel_secret = ENV["LINEPUBOT_SECRET"]
      config.channel_mid = ENV["LINEPUBOT_MID"]

    }
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/convos/index.html.erb
<h1>Test Convo Homepage</h1>
<hr>
<li><%= link_to "New Convo", new_convo_path %></li>
<hr>
<% @convos.each do |convo| %>
	<p><%= simple_format(convo.text)%></p><br>
	<hr>
<% end %>

app/views/convos/new.html.erb
<%= form_for @convo do |f| %>
	<%= f.label :text %>
	<br>
	<%= f.text_area :text, size: "80x15" %>
	<br>
	<%= f.submit(@convo.new_record? ? "Create Post" : "Update Post") %>
	<%= link_to "Cancel", :back %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LineBotTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>